name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # Install sagemath
      - run: sudo add-apt-repository -y universe
      - uses: awalsh128/cache-apt-pkgs-action@v1.4.2
        with:
          packages: sagemath
      # Install cargo
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
